name: Deploy Nuget for Windows


on:
  pull_request:
    tags:
    - 'v*'
    branches:
    - main
    
env:
  PATH_TO_PROJECTS: ${{ github.workspace }}\src
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace}}\output\
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'
  GITHUB_PACKAGES_URL: 'https://nuget.pkg.github.com/asvol/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: windows-2019
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: |
              7.x.x
              6.x.x
              5.x.x
              3.x.x

      - name: Restore dependencies
        run: |
          cd src
          dotnet restore

      - name: Build projects
        run: |
          cd src
          dotnet build -c Release --no-restore

      - name: Get version
        id: version
        uses: battila7/get-version-action@v2

      - name: Pack projects to Nuget 
        run: |
          cd src
          dotnet pack -c Release --no-build --no-restore -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: Push package to Nuget 
        run: |
          cd src
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL}}
          
      - name: Push package to github packages
        run: |
          cd src
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.GITHUB_PACKAGES_URL}}
          